'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowLeft,Plus,Check,CheckCheck,LayoutGrid,Target,CalendarDays,ChevronRight,Download,Upload,RefreshCw,Search,Network,Mic,Video,Activity,GraduationCap,PanelsTopLeft,Handshake,Trophy,Zap,Flag,Clock3,AlertCircle,Pencil,CloudCheck,Loader2,ListTodo,LockKeyhole,FileText} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {seed,State,Task,Project,statuses,stateSchema,progress,blocked} from '@/lib/marketing';
const icons=[Handshake,Network,Mic,Activity,Video,Network,GraduationCap,PanelsTopLeft];
const nav=[['overview','Обзор',LayoutGrid],['projects','Все проекты',PanelsTopLeft],['focus','Фокус и сроки',Target],['briefings','Брифинги',FileText]] as const;
const uid=()=>crypto.randomUUID();
const day=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});
const date=(v:string)=>v?new Date(v+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'}):'Срок не задан';
const statusClass=(s:string)=>s==='Выполнено'?'done':s==='В работе'?'active':s==='Ожидает'?'waiting':'new';
function Picker({value,onChange,items,label,labels}:{value:string;onChange:(v:string)=>void;items:string[];label:string;labels?:Record<string,string>}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{labels?.[i]||i}</SelectItem>)}</SelectContent></Select>}
function CloseMobileNavigation({view,projectId}:{view:string;projectId:string}){
 const {setOpenMobile}=useSidebar();
 useEffect(()=>{setOpenMobile(false)},[view,projectId,setOpenMobile]);
 return null;
}
export default function Home(){
const [state,setState]=useState<State>(seed),[version,setVersion]=useState(0),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[connected,setConnected]=useState(true);
const [view,setView]=useState('overview'),[projectId,setProjectId]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('Все'),[taskView,setTaskView]=useState('stages');
const [edit,setEdit]=useState<{project:string;task:Task;isNew:boolean}|null>(null),[meta,setMeta]=useState<Project|null>(null),[brief,setBrief]=useState(false),[briefDate,setBriefDate]=useState(day()),[briefText,setBriefText]=useState(''),[importData,setImportData]=useState<State|null>(null);
const busy=useRef(false),fileRef=useRef<HTMLInputElement>(null);
const versionRef=useRef(0),writeEpoch=useRef(0),loadedRef=useRef(false),fetching=useRef(false),draftOpen=useRef(false);
draftOpen.current=Boolean(edit||meta||brief||importData);
async function load(background=false){
 if(busy.current||fetching.current||(background&&(document.hidden||window.frameElement?.closest(".view")?.classList.contains("active")===false||draftOpen.current)))return;
 fetching.current=true;
 const epoch=writeEpoch.current,controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);
 try{
  const r=await fetch('/api/state',{cache:'no-store',signal:controller.signal});
  const b=await r.json() as {error?:string;state:State;version:number};
  if(!r.ok)throw new Error(b.error||'Не удалось загрузить проекты');
  const parsed=stateSchema.parse(b.state);
  if(epoch!==writeEpoch.current||busy.current||(background&&draftOpen.current)||b.version<versionRef.current)return;
  if(!loadedRef.current||b.version!==versionRef.current){setState(parsed);versionRef.current=b.version;setVersion(b.version)}
  loadedRef.current=true;setLoaded(true);setConnected(true);if(!background)setError('');
 }catch(e){
  if(epoch!==writeEpoch.current)return;
  setConnected(false);if(!background)setError(e instanceof Error?e.message:'Не удалось загрузить проекты');
 }finally{clearTimeout(timeout);fetching.current=false}
}
useEffect(()=>{
 void load();
 const sync=()=>{void load(true)};
 const disconnected=()=>setConnected(false);
 const interval=setInterval(sync,30000);
 window.addEventListener('focus',sync);window.addEventListener('online',sync);window.addEventListener('offline',disconnected);document.addEventListener('visibilitychange',sync);
 return()=>{clearInterval(interval);window.removeEventListener('focus',sync);window.removeEventListener('online',sync);window.removeEventListener('offline',disconnected);document.removeEventListener('visibilitychange',sync)};
},[]);
async function save(next:State,message:string){
 if(!loaded||busy.current)return false;
 busy.current=true;writeEpoch.current++;setSaving(true);setError('');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);
 try{
  next.history=[{id:uid(),date:new Date().toISOString(),text:message},...next.history].slice(0,1000);
  const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({state:next,version:versionRef.current})});
  const b=await r.json() as {error?:string;version:number};
  if(!r.ok)throw new Error(b.error||'Изменение не сохранено');
  versionRef.current=b.version;setVersion(b.version);setState(next);setConnected(true);toast.success(message);return true;
 }catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');return false}
 finally{clearTimeout(timeout);busy.current=false;setSaving(false)}
}
function openProject(p:Project){setProjectId(p.id);setView('detail');setQuery('');window.scrollTo({top:0,behavior:'smooth'})}
function addTask(p?:Project,stage?:string){const pr=p||state.projects[0];setEdit({project:pr.id,isNew:true,task:{id:uid(),title:'',stage:stage||pr.tasks[0]?.stage||'Новый этап',owner:pr.owner,due:'',status:'Новая',result:'',depends:[]}})}
async function toggle(p:Project,t:Task){if(t.status!=='Выполнено'&&blocked(t,state).length){toast.error('Сначала завершите задачи, от которых зависит этот шаг');return;}const next=structuredClone(state);const n=next.projects.find(x=>x.id===p.id)!.tasks.find(x=>x.id===t.id)!;n.status=t.status==='Выполнено'?'Новая':'Выполнено';await save(next,n.status==='Выполнено'?`Готово: ${t.title} · +10 очков`:`Задача возвращена в работу: ${t.title}`)}
async function submitTask(e:React.FormEvent){e.preventDefault();if(!edit)return;const t={...edit.task,title:edit.task.title.trim(),stage:edit.task.stage.trim()};if(!t.title||!t.stage)return;if(t.status==='Выполнено'&&blocked(t,state).length){toast.error('Есть незавершённые зависимости');return;}const next=structuredClone(state);const p=next.projects.find(x=>x.id===edit.project)!;if(edit.isNew)p.tasks.push(t);else p.tasks=p.tasks.map(x=>x.id===t.id?t:x);if(await save(next,edit.isNew?`Добавлена задача: ${t.title}`:`Обновлена задача: ${t.title}`))setEdit(null)}
function download(contents:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([contents],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const all=state.projects.flatMap(p=>p.tasks.map(t=>({...t,p}))),done=all.filter(t=>t.status==='Выполнено').length,stagesDone=state.projects.reduce((n,p)=>n+[...new Set(p.tasks.map(t=>t.stage))].filter(g=>p.tasks.filter(t=>t.stage===g).every(t=>t.status==='Выполнено')).length,0),xp=done*10+stagesDone*30,percent=Math.round(done/Math.max(1,all.length)*100),complete=state.projects.filter(p=>progress(p)===100).length;
const today=day(),overdue=all.filter(t=>t.due&&t.due<today&&t.status!=='Выполнено'),scheduled=all.filter(t=>t.due&&t.status!=='Выполнено').sort((a,b)=>a.due.localeCompare(b.due));
const project=state.projects.find(p=>p.id===projectId),visible=state.projects.filter(p=>(filter==='Все'||p.priority===filter)&&(p.title+' '+p.description+' '+p.tasks.map(t=>t.title).join(' ')).toLowerCase().includes(query.toLowerCase()));
function taskRow(p:Project,t:Task){const deps=blocked(t,state);return <div className={'task-row '+(t.status==='Выполнено'?'is-done':'')} key={t.id}><Checkbox className="task-check" checked={t.status==='Выполнено'} disabled={!loaded||saving} onCheckedChange={()=>toggle(p,t)} aria-label={`Выполнено: ${t.title}`}/><button className="task-body" onClick={()=>setEdit({project:p.id,task:structuredClone(t),isNew:false})}><span className="task-title">{t.title}</span><span className="task-meta">{t.owner||'Ответственный не назначен'}<span>·</span><span className={t.due&&t.due<today&&t.status!=='Выполнено'?'late':''}>{date(t.due)}</span>{deps.length>0&&<span className="dependency"><LockKeyhole size={12}/> {deps.length} завис.</span>}</span>{t.result&&<span className="task-result">{t.result}</span>}</button><span className={'status '+statusClass(t.status)}>{t.status}</span><button className="icon-button task-edit" aria-label={`Изменить: ${t.title}`} onClick={()=>setEdit({project:p.id,task:structuredClone(t),isNew:false})}><Pencil size={15}/></button></div>}
function card(p:Project,i:number){const Icon=icons[state.projects.findIndex(x=>x.id===p.id)]||Flag;const n=p.tasks.filter(t=>t.status==='Выполнено').length;const groups=[...new Set(p.tasks.map(t=>t.stage))];const next=p.tasks.find(t=>t.status!=='Выполнено'&&!blocked(t,state).length);return <button key={p.id} className="project-card" onClick={()=>openProject(p)} style={{animationDelay:`${i*35}ms`}}><div className="card-top"><span className={'project-icon icon-'+p.id}><Icon size={23}/></span><span className={'priority '+p.priority}>{p.priority} · {p.priority==='P0'?'В первую очередь':p.priority==='P1'?'Высокий':'Проектирование'}</span><ArrowUpRight className="card-arrow" size={20}/></div><h3>{p.short}</h3><p className="card-description">{p.description}</p><div className="stage-track">{groups.map(g=><span key={g} title={g}><i style={{width:`${p.tasks.filter(t=>t.stage===g&&t.status==='Выполнено').length/p.tasks.filter(t=>t.stage===g).length*100}%`}}/></span>)}</div><div className="card-count"><span>{n} из {p.tasks.length} задач</span><strong>{progress(p)}%</strong></div><div className="card-next"><span>{next?'СЛЕДУЮЩИЙ ШАГ':'РЕЗУЛЬТАТ'}</span><p>{next?.title||'Все задачи завершены'}</p></div><div className="card-footer"><span className="mini-avatar">{p.owner?'КБ':'?'}</span><span>{p.owner||'Назначить ответственного'}</span><ChevronRight size={16}/></div></button>}
return <SidebarProvider><CloseMobileNavigation view={view} projectId={projectId}/><Sidebar className="side-panel"><SidebarHeader><div className="brand">люди<span>КЛИНИКА СОВРЕМЕННОЙ ХИРУРГИИ</span></div><div className="workspace-label">РАБОЧЕЕ ПРОСТРАНСТВО</div></SidebarHeader><SidebarContent><SidebarGroup><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>{setView(id);setQuery('')}} className="nav-item"><Icon/><span>{label}</span>{id==='projects'&&<b className="nav-count">{state.projects.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup><div className="side-label">ПРОЕКТЫ</div>{state.projects.map((p,i)=>{const Icon=icons[i]||Flag;return <button key={p.id} className={'side-project '+(view==='detail'&&projectId===p.id?'selected':'')} onClick={()=>openProject(p)}><Icon size={16}/><span>{p.short}</span><span className={'small-priority '+p.priority}>{p.priority}</span></button>})}</SidebarGroup></SidebarContent><SidebarFooter><div className="side-level"><div><Zap size={17}/><b>Уровень {Math.floor(xp/200)+1}</b><span>{xp} очков</span></div><Progress value={xp%200/2}/><small>{200-xp%200} очков до следующего уровня</small></div><div className="profile"><div className="avatar">КБ</div><div><strong>Константин Бадьян</strong><small>Хирургическое направление</small></div></div></SidebarFooter></Sidebar>
<main className="main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger aria-label="Открыть меню маркетинга"/><span>Люди</span><ChevronRight size={14}/><strong>Маркетинг</strong></div><div className="top-right"><span className="save-state" aria-live="polite">{saving?<><Loader2 className="spin" size={15}/> Сохраняем</>:error?<><AlertCircle size={15}/> Есть ошибка</>:!connected?<><RefreshCw size={15}/> Восстанавливаем связь</>:loaded?<><CloudCheck size={15}/> Онлайн · автосинхронизация</>:'Загрузка проектов'}</span><span className="top-date">{date(today)} {today.slice(0,4)}</span><div className="avatar small">КБ</div></div></header>
<div className="mobile-marketing-navigation">
<nav className="marketing-tabs" aria-label="Разделы маркетинга">{nav.map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>{setView(id);setQuery('')}}>{label}</button>)}</nav>
<label className="mobile-project-picker"><span>Проект</span><select aria-label="Выбрать маркетинговый проект" value={view==='detail'?projectId:''} onChange={e=>{const p=state.projects.find(p=>p.id===e.target.value);if(p)openProject(p)}}><option value="" disabled>Выберите проект · {state.projects.length}</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.short}</option>)}</select></label>
</div><div className="page-content">{error&&<div className="error-banner" role="alert"><AlertCircle size={20}/><span>{error} Несохранённый ввод остаётся в форме.</span><button onClick={()=>load()}>Обновить данные</button></div>}{!connected&&<div className="offline-banner" role="status">Связь с сервером потеряна. Повторяем подключение автоматически. Последние загруженные данные остаются на экране.</div>}
{view!=='detail'&&<div className="page-heading"><div><div className="eyebrow">МАРКЕТИНГ КЛИНИКИ</div><h1>{view==='overview'?'Работа с маркетингом':view==='projects'?'Все проекты':view==='focus'?'Фокус и сроки':'Брифинги и решения'}</h1><p>{view==='overview'?'От решений на встрече — к завершённым проектам.':view==='projects'?'Восемь направлений. У каждого — понятный следующий шаг.':view==='focus'?'Контрольные даты, срочные шаги и вопросы для решения.':'Каждая встреча продолжает предыдущую.'}</p></div><button className="primary-button" disabled={!loaded||saving} onClick={()=>view==='briefings'?setBrief(true):addTask()}><Plus size={18}/>{view==='briefings'?'Записать брифинг':'Добавить задачу'}</button></div>}
{(view==='overview'||view==='projects')&&<>{view==='overview'&&<><section className="metrics"><div><span className="metric-label">Проекты в работе</span><strong>{state.projects.length-complete}<small>/ {state.projects.length}</small></strong><span className="metric-note">{complete} завершено</span></div><div><span className="metric-label">Закрытые задачи</span><strong>{done}<small>/ {all.length}</small></strong><span className="metric-note">{percent}% от общего плана</span></div><div><span className="metric-label">Первый приоритет</span><strong>{state.projects.filter(p=>p.priority==='P0'&&progress(p)<100).length}<small>проекта</small></strong><span className="metric-note">Требуют внимания сейчас</span></div><div><span className="metric-label">Прогресс команды <Zap size={15}/></span><strong>{xp}<small>очков</small></strong><span className="metric-note">{stagesDone} этапов завершено</span></div></section><section className="focus-strip"><div className="focus-intro"><span className="focus-kicker"><Target size={17}/> ФОКУС СЕЙЧАС</span><h2>Три ключевых <br/>направления</h2><p>По итогам встречи<br/>9 сентября</p></div><div className="focus-items">{state.projects.filter(p=>p.priority==='P0').map((p,i)=><button key={p.id} onClick={()=>openProject(p)}><span className="focus-number">0{i+1}</span><span><strong>{p.short}</strong><small>{p.id==='partners'?'Максимальный приоритет · срок не задан':p.id==='krug'?'Приезд эксперта · 17 сентября':'Выбрать тему · до 15 сентября'}</small></span><ArrowUpRight size={18}/></button>)}</div></section></>}
<div className="section-heading"><div><h2>Портфель проектов <span>{state.projects.length}</span></h2></div><div className="project-tools"><div className="filters">{['Все','P0','P1','P2'].map(f=><button key={f} className={filter===f?'chosen':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти проект" aria-label="Найти проект"/></label></div></div><div className={view==='overview'?'portfolio-layout':''}><section className="project-grid">{visible.map(card)}{!visible.length&&<div className="empty-state">По запросу ничего не найдено. Попробуйте другое название.</div>}</section>{view==='overview'&&<aside className="right-rail"><section className="journey"><div className="rail-heading"><h3>Общий прогресс</h3><Trophy size={18}/></div><div className="progress-orbit" style={{'--angle':`${percent*3.6}deg`} as React.CSSProperties}><div><strong>{percent}<span>%</span></strong><small>плана выполнено</small></div></div><p>{done===0?'Начните с одного следующего шага':`Уже завершено ${done} задач`}</p><div className="reward"><CheckCheck size={20}/><div><b>Первый результат</b><small>{done?'Получено · первая задача закрыта':'Закройте первую задачу'}</small></div><span>{done?'✓':'10'}</span></div><div className="reward"><Flag size={20}/><div><b>Этап пройден</b><small>{stagesDone?'Получено · этап завершён':'Завершите все задачи этапа'}</small></div><span>{stagesDone?'✓':'+30'}</span></div><small className="reward-note">10 очков за задачу, 30 — за этап. Прогресс отражает выполнение плана, а не эффективность маркетинга.</small></section><section className="rail-dates"><div className="rail-heading"><h3>Контрольные даты</h3><CalendarDays size={18}/></div><button onClick={()=>openProject(state.projects.find(p=>p.id==='webinar')!)}><span className="date-tile"><b>15</b>СЕН</span><span><b>Тема вебинара</b><small>Константин + Альвина</small></span></button><button onClick={()=>openProject(state.projects.find(p=>p.id==='krug')!)}><span className="date-tile"><b>17</b>СЕН</span><span><b>Приезд С. В. Круга</b><small>Кампания и съёмка</small></span></button><p>Остальные сроки и единоличных ответственных нужно определить.</p></section><section className="brief-note"><FileText size={19}/><h3>Следующий брифинг</h3><p>Что планировали → что сделано → результат → проблема → следующий шаг.</p><button className="text-button" onClick={()=>setView('briefings')}>Открыть журнал <ChevronRight size={15}/></button></section></aside>}</div></>}
{view==='detail'&&project&&<><button className="back-link" onClick={()=>setView('projects')}><ArrowLeft size={17}/> Все проекты</button><div className="detail-heading"><div><span className={'priority '+project.priority}>{project.priority} · {project.priority==='P0'?'В первую очередь':'Проект'}</span><h1>{project.title}</h1><p>{project.description}</p></div><button className="secondary-button" onClick={()=>setMeta(structuredClone(project))}><Pencil size={16}/> Паспорт проекта</button></div><div className="project-context"><span><b>Ответственный</b>{project.owner||'Не назначен'}</span><span><b>Участники</b>{project.participants}</span><span><b>Завершено</b>{project.tasks.filter(t=>t.status==='Выполнено').length} / {project.tasks.length} задач</span></div><div className="project-note"><AlertCircle size={18}/><p>{project.note}</p></div><div className="detail-progress"><Progress value={progress(project)}/><strong>{progress(project)}%</strong></div><div className="section-heading"><Tabs value={taskView} onValueChange={setTaskView}><TabsList><TabsTrigger value="stages">По этапам</TabsTrigger><TabsTrigger value="board">По статусам</TabsTrigger></TabsList></Tabs><button className="primary-button" disabled={!loaded||saving} onClick={()=>addTask(project)}><Plus size={17}/> Добавить задачу</button></div>{taskView==='stages'?<div className="stages">{[...new Set(project.tasks.map(t=>t.stage))].map((stage,i)=>{const ts=project.tasks.filter(t=>t.stage===stage),n=ts.filter(t=>t.status==='Выполнено').length;return <section key={stage} className="stage"><div className="stage-heading"><span className={'stage-number '+(n===ts.length?'completed':'')}>{n===ts.length?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><h2>{stage}</h2><span>{n}/{ts.length}</span><button className="icon-button" aria-label={`Добавить задачу в этап ${stage}`} onClick={()=>addTask(project,stage)}><Plus size={17}/></button></div>{ts.map(t=>taskRow(project,t))}</section>})}</div>:<div className="kanban">{statuses.map(status=><section key={status}><h3><span className={'status '+statusClass(status)}>{status}</span><span>{project.tasks.filter(t=>t.status===status).length}</span></h3>{project.tasks.filter(t=>t.status===status).map(t=><button className="kanban-card" key={t.id} onClick={()=>setEdit({project:project.id,task:structuredClone(t),isNew:false})}><small>{t.stage}</small><b>{t.title}</b><span>{t.owner||'Не назначен'}</span><span>{date(t.due)}</span></button>)}{!project.tasks.some(t=>t.status===status)&&<p className="board-empty">Пока нет задач</p>}</section>)}</div>}</>}
{view==='focus'&&<div className="focus-page"><section className="stage"><div className="stage-heading"><Clock3 size={21}/><h2>Задачи с датой</h2><span>{scheduled.length}</span></div>{scheduled.map(t=>taskRow(t.p,t))}{!scheduled.length&&<p className="empty-state">Открытых задач со сроком нет.</p>}<div className="event-row"><CalendarDays size={21}/><span><b>17 сентября 2026</b> — приезд Сергея Викторовича Круга</span><button className="text-button" onClick={()=>openProject(state.projects.find(p=>p.id==='krug')!)}>К проекту <ChevronRight size={16}/></button></div></section><section className="stage"><div className="stage-heading"><Target size={21}/><h2>Следующие шаги P0</h2></div>{state.projects.filter(p=>p.priority==='P0').map(p=>{const t=p.tasks.find(t=>t.status!=='Выполнено'&&!blocked(t,state).length);return t?<div key={p.id}><div className="task-project-label">{p.short}</div>{taskRow(p,t)}</div>:null})}</section><section className="decision-panel"><h2>Нужно определить</h2><div><strong>{all.filter(t=>!t.owner&&t.status!=='Выполнено').length}</strong><span>задач без единоличного ответственного</span></div><div><strong>{all.filter(t=>!t.due&&t.status!=='Выполнено').length}</strong><span>задач без контрольной даты</span></div><div><strong>{overdue.length}</strong><span>задач с истёкшим сроком</span></div><p>В исходном дебрифе часть исполнителей указана совместно. Назначения и сроки можно зафиксировать в карточке каждой задачи.</p></section></div>}
{view==='briefings'&&<div className="brief-layout"><section><div className="brief-process">Планировали <ChevronRight/> Сделали <ChevronRight/> Результат <ChevronRight/> Следующий шаг</div>{state.briefings.slice().reverse().map(b=><article className="brief-card" key={b.id}><div><CalendarDays size={18}/><b>{date(b.date)} {b.date.slice(0,4)}</b><span>Маркетинг</span></div><p>{b.text}</p></article>)}</section><aside className="history"><h2>Лента изменений</h2>{state.history.length?state.history.slice(0,30).map(h=><div key={h.id}><span className="history-dot"/><p>{h.text}<small>{new Date(h.date).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></p></div>):<p className="empty-history">Здесь появятся закрытые задачи, назначения и новые решения.</p>}</aside></div>}
<footer className="footer"><span>Люди · Маркетинг <span className="footer-separator">/</span> Основа: дебриф 09.09.2026</span><div><button disabled={!loaded} onClick={()=>download(JSON.stringify(state,null,2),'marketing-projects-'+day()+'.json','application/json')}><Download size={15}/> Экспорт данных</button><button disabled={!loaded||saving} onClick={()=>fileRef.current?.click()}><Upload size={15}/> Импорт</button><button onClick={()=>load()} disabled={saving}><RefreshCw size={15}/> Обновить</button></div></footer>
<input hidden type="file" accept=".json,application/json" ref={fileRef} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>1500000)throw new Error();setImportData(stateSchema.parse(JSON.parse(await f.text())))}catch{toast.error('Файл не подходит. Выберите экспорт данных этого дашборда.')}e.target.value=''}}/>
</div></main>
<Dialog open={!!edit} onOpenChange={o=>{if(!o&&!saving)setEdit(null)}}><DialogContent className="task-dialog"><DialogTitle>{edit?.isNew?'Новая задача':'Карточка задачи'}</DialogTitle><DialogDescription>Ответственный, срок и результат выполнения.</DialogDescription>{edit&&<form onSubmit={submitTask} className="task-form"><label>Проект<Picker label="Проект" value={edit.project} labels={Object.fromEntries(state.projects.map(p=>[p.id,p.short]))} items={edit.isNew?state.projects.map(p=>p.id):[edit.project]} onChange={id=>setEdit({...edit,project:id,task:{...edit.task,stage:state.projects.find(p=>p.id===id)!.tasks[0]?.stage||'Новый этап'}})}/><small>{state.projects.find(p=>p.id===edit.project)?.title}</small></label><label>Задача<input required maxLength={300} value={edit.task.title} onChange={e=>setEdit({...edit,task:{...edit.task,title:e.target.value}})}/></label><label>Этап<input required list="stages-list" maxLength={100} value={edit.task.stage} onChange={e=>setEdit({...edit,task:{...edit.task,stage:e.target.value}})}/><datalist id="stages-list">{[...new Set(state.projects.find(p=>p.id===edit.project)!.tasks.map(t=>t.stage))].map(s=><option key={s}>{s}</option>)}</datalist></label><div className="form-cols"><label>Ответственный<input placeholder="Имя одного ответственного" maxLength={120} value={edit.task.owner} onChange={e=>setEdit({...edit,task:{...edit.task,owner:e.target.value}})}/></label><label>Контрольная дата<input type="date" value={edit.task.due} onChange={e=>setEdit({...edit,task:{...edit.task,due:e.target.value}})}/></label></div><label>Статус<Picker label="Статус задачи" value={edit.task.status} items={[...statuses]} onChange={v=>setEdit({...edit,task:{...edit.task,status:v as Task['status']}})}/></label><label>Результат / что мешает / следующий шаг<textarea rows={3} maxLength={5000} placeholder="Ссылка на материал, принятое решение или причина ожидания" value={edit.task.result} onChange={e=>setEdit({...edit,task:{...edit.task,result:e.target.value}})}/></label>{edit.task.depends.length>0&&<div className="dependencies"><b>Сначала необходимо</b>{edit.task.depends.map(id=><span key={id}>{all.find(t=>t.id===id)?.title||id}</span>)}</div>}<button className="primary-button" type="submit" disabled={saving||!loaded}>{saving?<Loader2 className="spin" size={17}/>:<Check size={17}/>} Сохранить задачу</button></form>}</DialogContent></Dialog>
<Dialog open={!!meta} onOpenChange={o=>!o&&!saving&&setMeta(null)}><DialogContent><DialogTitle>Паспорт проекта</DialogTitle><DialogDescription>Общие договорённости и ответственный за результат.</DialogDescription>{meta&&<form className="task-form" onSubmit={async e=>{e.preventDefault();const next=structuredClone(state);next.projects=next.projects.map(p=>p.id===meta.id?{...meta,tasks:p.tasks}:p);if(await save(next,`Обновлён проект: ${meta.short}`))setMeta(null)}}><label>Название<input required maxLength={200} value={meta.title} onChange={e=>setMeta({...meta,title:e.target.value,short:e.target.value.slice(0,100)})}/></label><label>Ответственный<input maxLength={120} placeholder="Не назначен" value={meta.owner} onChange={e=>setMeta({...meta,owner:e.target.value})}/><small>Назначение на проект не меняет исполнителей его задач.</small></label><label>Приоритет<Picker label="Приоритет" items={['P0','P1','P2']} value={meta.priority} onChange={v=>setMeta({...meta,priority:v as Project['priority']})}/></label><label>Участники<input maxLength={300} value={meta.participants} onChange={e=>setMeta({...meta,participants:e.target.value})}/></label><label>Важные договорённости<textarea maxLength={3000} rows={4} value={meta.note} onChange={e=>setMeta({...meta,note:e.target.value})}/></label><button type="submit" disabled={saving} className="primary-button">Сохранить</button></form>}</DialogContent></Dialog>
<Dialog open={brief} onOpenChange={setBrief}><DialogContent><DialogTitle>Новый брифинг</DialogTitle><DialogDescription>Зафиксируйте решения. Новые задачи добавьте в соответствующие проекты.</DialogDescription><form className="task-form" onSubmit={async e=>{e.preventDefault();const next=structuredClone(state);next.briefings.push({id:uid(),date:briefDate,text:briefText.trim()});if(await save(next,`Записан брифинг ${date(briefDate)}`)){setBrief(false);setBriefText('')}}}><label>Дата<input required type="date" value={briefDate} onChange={e=>setBriefDate(e.target.value)}/></label><label>Решения и следующий шаг<textarea required rows={9} maxLength={20000} value={briefText} onChange={e=>setBriefText(e.target.value)} placeholder="Что выполнено? Каков результат? Что мешает? Какие новые задачи, ответственные и сроки?"/></label><button className="primary-button" disabled={saving||!briefText.trim()} type="submit">Сохранить брифинг</button></form></DialogContent></Dialog>
<Dialog open={!!importData} onOpenChange={o=>!o&&setImportData(null)}><DialogContent><DialogTitle>Заменить данные из файла?</DialogTitle><DialogDescription>Будут загружены {importData?.projects.length} проектов. Сначала сохраните текущий экспорт, если нужна резервная копия.</DialogDescription><button className="secondary-button" onClick={()=>download(JSON.stringify(state,null,2),'marketing-backup-'+day()+'.json','application/json')}>Скачать текущую копию</button><button className="primary-button" disabled={saving} onClick={async()=>{if(importData&&await save(structuredClone(importData),'Данные восстановлены из файла')){setImportData(null);setView('overview')}}}>Заменить данные</button></DialogContent></Dialog>
<Toaster position="bottom-right" richColors closeButton/>
</SidebarProvider>}
